### ISSUE TITLE
Poor speaker sound quality

### ISSUE THREAD

**Issue by Vikkeb** [4ragaki/android_device_xiaomi_elish#3]
The sound quality from the speakers are very bad using both Lineage & Pixel Experience ROM.
The sound is very muffled and lacking any type of clarity, and I also think the volume control has too many steps to adjust the volume.

**Comment by 4ragaki** [comment]
xiaomi may did some dolby config in their proprietary code other than dax-default.xml

you can try this conf from pixelos:[dax-default.xml.txt](https://github.com/4ragaki/android_device_xiaomi_elish/files/14627536/dax-default.xml.txt)

enable adb,root debugging for los; connect via usb; spawn terminal

adb root
adb remount
adb push <dax-default.xml> /vendor/etc/dolby/dax-default.xml

reboot and check.

**Comment by Vikkeb** [comment]
Sorry, that conf file made no difference.
The sound is working fine when running ArrowOS rom, so I tried pushing the conf from that rom but it also didn't make any difference...

**Comment by 4ragaki** [comment]
I checked the sound yesterday and find it do improve in some way. can you paste your shell input and output here? or pull the config to your computer and compare using tools like diff/meld

**Comment by 4ragaki** [comment]
> I checked the sound yesterday and find it do improve in some way. can you paste your shell input and output here? or pull the config to your computer and compare using tools like diff/meld

and don't use arrowOS Dolby config, they build using stock vendor(not sure for newer version), that's almost what packed in right here.

**Comment by Vikkeb** [comment]
Here's my input/output pushing the provided file, and to my ears it doesn't really make a difference:

* C:\Users\Vikkeb\Desktop\platform-tools>adb root
  - daemon not running; starting now at tcp:5037
  - daemon started successfully
  - restarting adbd as root
* C:\Users\Vikkeb\Desktop\platform-tools>adb remount
  - remount succeeded
* C:\Users\Vikkeb\Desktop\platform-tools>adb push dax-default.xml /vendor/etc/dolby/dax-default.xml
  - dax-default.xml: 1 file pushed, 0 skipped. 82.2 MB/s (85049 bytes in 0.001s)
* C:\Users\Vikkeb\Desktop\platform-tools>adb reboot

**Comment by Vikkeb** [comment]
I'm not sure Dolby Atmos is working at all, changing profile and presets or turning it on and off in the sound settings does not change the sound at all. I have also pulled the config and compared it, and its the same on device as the one you provided.

**Comment by 4ragaki** [comment]
The Atmos service is running, grep dms in logcat will get it's log. but settings is made by reverse engineering of the custom rom community, may need further work and investigation. hence this won't get fixed soon.


For the sound effect problem, if you mind, The final option is drop Atmos entirely, but it should be though without rebuilding from source.

**Comment by 4ragaki** [comment]
try this build:https://github.com/4ragaki/android_device_xiaomi_elish/releases/tag/sound-trial

**Comment by Vikkeb** [comment]
Thanks, will give it a try when I have access to my device again.
But it wont be for another 10 days unfortunately.

**Comment by Coxxs** [comment]
I think it's because the right channel is missing. You can open [this video](https://www.youtube.com/watch?v=91BUM3WhCfo) in the browser or YouTube app to test it.
In ArrowOS, the left/right channel works fine, and when the user rotates the tablet, it also automatically changes the speaker to reposition the audio.
In PixelExperience `sound-trial` build, the right channel seems to be missing.

**Comment by 4ragaki** [comment]
> I think it's because the right channel is missing. You can open [this video](https://www.youtube.com/watch?v=91BUM3WhCfo) in the browser or YouTube app to test it. In ArrowOS, the left/right channel works fine, and when the user rotates the tablet, it also automatically changes the speaker to reposition the audio. In PixelExperience `sound-trial` build, the right channel seems to be missing.

right channel missing is the trial build specific,and it was fixed : https://github.com/4ragaki/android_device_xiaomi_elish/releases/tag/sound-trial

Atmos support was dropped, and I believe "reposition the speakers" is an atmos feature.

**Comment by Vikkeb** [comment]
sorry for the delay, unfortunately the latest trial build made no improvement and the sound issue remains the same. 
So I guess we can rule out that Atmos and the configs are causing the problem in this case.

**Comment by 4ragaki** [comment]
this is my final guess, download and unzip this [acdb.zip](https://github.com/4ragaki/android_device_xiaomi_elish/files/14918767/acdb.zip)

and the old routine, spawn terminal: 
```bash
adb root 

adb remount

adb push acdbdata /vendor/etc/
```

reboot and check.

you can do this in both older release and trial build, and leave your feedback.

**Comment by Vikkeb** [comment]
Thanks for trying, but no change.

Just to give you some context.
This is a sample I recorded with my phone from both PE and MIUI. Both recorded from same distance and volume (very unscientific), but you can still hear that PE has a very diffused sound compared to MIUI.

https://github.com/4ragaki/android_device_xiaomi_elish/assets/8999139/0667d36e-47e6-48df-9c4f-0716fa537ab7

**Comment by 4ragaki** [comment]
use the 1230 release and enable atmos.

push the acdb files uploaded before.

download and unzip [conf.zip](https://github.com/4ragaki/android_device_xiaomi_elish/files/14934579/conf.zip)

```
...

adb push * /vendor/etc/
```

reboot and check

**Comment by 4ragaki** [comment]
This should be it: elish uses different amplifier config and firmwares than normal two speakers phone.

give this a try: https://github.com/4ragaki/android_device_xiaomi_elish/releases/tag/amplifier-fix

**Comment by Vikkeb** [comment]
> This should be it: elish uses different amplifier config and firmwares than normal two speakers phone.
> 
> give this a try: https://github.com/4ragaki/android_device_xiaomi_elish/releases/tag/amplifier-fix

That was it! Now speaker works as expected. 
Maybe there could be a version with this amplifier config and atmos at the same time?

**Comment by 4ragaki** [comment]
Atmos is shipped in this amplifier-fix build,if you are missing the atmos setting maybe a clean flash will fix.

**Comment by Vikkeb** [comment]
Yes now I can see that, I just missed the atmos option it in the sound settings.
Thank you!

**Comment by Coxxs** [comment]
Audio works great now! Volume sometimes goes up and down randomly in Arrow OS/GSI, but seems fine in `amplifier-fix` Pixel Experience. Thanks again!
